### ISSUE TITLE
支持less全局样式

### ISSUE THREAD

**Issue by ZhangEryi** [NervJS/tarojs-plugin-platform-nextjs#12]
<img width="636" alt="image" src="https://user-images.githubusercontent.com/26322447/198992320-bbf79763-5586-4140-bfe0-a60ad986509a.png">
未支持less文件全局样式导入，目前只支持了scss和sass

**Comment by SyMind** [comment]
@ZhangEryi 是的，今天晚点 fix 这个问题。

**Comment by ZhangEryi** [comment]
> @ZhangEryi 是的，今天晚点 fix 这个问题。

<img width="598" alt="image" src="https://user-images.githubusercontent.com/26322447/198993608-cb876914-fa30-48a5-a148-f8ace109508f.png">
试了下 加上less就可以了，辛苦聪哥，我没可能没权限

**Comment by SyMind** [comment]
@ZhangEryi 额，你谁啊。

**Comment by SyMind** [comment]
@ZhangEryi 是这里没错，那个可以尝试直接 pr。

**Comment by ZhangEryi** [comment]
> 

对 项目用了next-with-less，我在nextjs内build提示找不到@taror/components；
聪哥能帮忙提一下吗？我是健康这边的fe

**Comment by SyMind** [comment]
@ZhangEryi ok 了解了。因为 taro 默认就支持 less，所以我将尝试让该插件来默认支持 less。

**Comment by SyMind** [comment]
@ZhangEryi 插件默认已经支持 Less，并发布了 2.0.5 版本。

**Comment by SyMind** [comment]
@ZhangEryi 若问题解决，将关闭该 issue。
