### ISSUE TITLE
目前这个插件建议使用在生产环境中吗？

### ISSUE THREAD

**Issue by lewinloo** [NervJS/tarojs-plugin-platform-nextjs#19]

**Comment by SyMind** [comment]
@lewinloo 可以。

在一年前就已经用于线上，因为其底层是基于 Next.js 实现的，插件仅负责转换工作，所以其运行得益于 Next.js 十分稳定且线上 LCP 80分位在 1s 以内。

若你存在任何疑问，可以添加我的微信 SharpYourMind，我可以解答你的任何问题。
