### ISSUE TITLE
h5的postcss配置貌似对next无效

### ISSUE THREAD

**Issue by denzhengwei** [NervJS/tarojs-plugin-platform-nextjs#22]
taro用了nextjs插件之后h5页面布局变得很怪，并且html多了个style="font-size: 40px;"大佬知道怎么回事嘛？taro配置文件/config/index.js里面h5的postcss配置貌似对next无效

**Comment by SyMind** [comment]
@denzhengwei 目前对 postcss 配置暂未支持，因工作原因这块功能一致没有补齐。
html 上 style="font-size: 40px;" 是同步 Taro h5 的实现，通过 rem 单位进行移动端适配。

**Comment by denzhengwei** [comment]
@SyMind 我现在想用taro+next插件开发响应式web应用，怎样配置使h5的postcss 配置对next生效呢？根据指引启动命令npx taro build --type nextjs --watch好像不会加载h5的配置

**Comment by SyMind** [comment]
@denzhengwei 该插件设计时并未考虑过响应式 web 应用，而且十分抱歉，我也没有充裕的时间去考虑这个问题。
当前这个项目正在寻求一个维护者，若你有兴趣，可以添加我的微信 SharpYourMind，我会尽量解答你的任何问题。

**Comment by denzhengwei** [comment]
感谢，我目前的能力还不足以维护这个项目，哈哈哈。现在已经放弃全平台编译了，用nextjs继续web项目

**Comment by SyMind** [comment]
https://github.com/NervJS/tarojs-plugin-platform-nextjs/issues/1

**Comment by SyMind** [comment]
@denzhengwei 已经发布 2.1.0 版本，以完整支持 Taro 的 postcss 配置。
