### ISSUE TITLE
不支持nextjs么，执行npx taro build --type nextjs --watch命令报错了

### ISSUE THREAD

**Issue by huliang1996618** [NervJS/tarojs-plugin-platform-nextjs#23]
Taro v3.4.14

(node:22684) UnhandledPromiseRejectionWarning: Error: 不存在编译平台 nextjs

**Comment by SyMind** [comment]
@huliang1996618 是否按照 readme 中的步骤，将插件添加到了 taro 的配置中。

**Comment by huliang1996618** [comment]
> @huliang1996618 是否按照 readme 中的步骤，将插件添加到了 taro 的配置中。

![image](https://user-images.githubusercontent.com/19297983/231650336-2b687626-3cd5-41e1-9aad-af054c312c26.png)
![image](https://user-images.githubusercontent.com/19297983/231650416-37aba4dd-4438-4a4a-931d-4a8f76ccf6f0.png)
都加上了

**Comment by SyMind** [comment]
@huliang1996618 了解了，可能是插件间有冲突，我一会尝试复现一下。

**Comment by huliang1996618** [comment]
> @huliang1996618 了解了，可能是插件间有冲突，我一会尝试复现一下。

麻烦了，要是有进展麻烦指导下，谢谢

**Comment by SyMind** [comment]
@huliang1996618 我尝试使用 `Taro v3.4.14` 来复现你的问题，但是我没有成功。
另外，由于你的 React 版本为 `^17.0.2`，需要安装 next 的版本为 `^12.3.2`。
